### ISSUE TITLE
Watch multiple namespaces?

### ISSUE THREAD

**Issue by ninjaslothx** [datastax/cass-operator#110]
I see the container spec has an env variable for WATCH_NAMESPACE. 
https://github.com/datastax/cass-operator/blob/master/docs/user/cass-operator-manifests-v1.17.yaml#L6308

Is it possible to have the operator watch multiple or all namespaces?

**Comment by jimdickinson** [comment]
Yes, that env var can accept a comma delimited list of namespaces. Clearing it should have one operator watch all namespaces.

source: https://sdk.operatorframework.io/docs/golang/quickstart/#manager

**Comment by ninjaslothx** [comment]
Thank you! Works as described.
