### ISSUE TITLE
Support "Seed Hinting"

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#131]
As we look to start supporting C* clusters that span K8s clusters we need to start adding some building blocks around the seeds list. Currently, cass-operator configures the seed list with the DNS name for the DC seed service. If a user specifies a seed entry (or entries) in their `spec.config.cassandra-yaml.seeds` YAML path we should not override it and simply append the value for this CRs DC.

**Comment by bradfordcp** [comment]
It looks like the path I mentioned above `spec.config.cassandra-yaml.seeds` does NOT exist. The correct path would be `spec.config.cluster-info.seeds`. See https://github.com/datastax/cass-config-builder/blob/master/README.md#cluster-info-key for more information.

**Comment by jimdickinson** [comment]
@bradfordcp do you think what we've got for `additionalSeeds` satisfies this?

**Comment by bradfordcp** [comment]
Yep, closing
