### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by devdattakulkarni** [datastax/cass-operator#134]
This link is referred to in the User documentation page. But it is giving 404.

https://github.com/datastax/cass-operator/blob/master/docs/user/cass-operator-manifests.yaml

**Comment by johnsmartco** [comment]
Ok yeah, @devdattakulkarni is correct that the link in the readme at https://github.com/datastax/cass-operator/tree/master/docs/user -- in the Deploy the operator section, https://github.com/datastax/cass-operator/tree/master/docs/user#deploy-the-operator -- incorrectly links to <a href="/datastax/cass-operator/blob/master/docs/user/cass-operator-manifests.yaml">operator-manifests YAML</a>.   

Need to change the target to https://github.com/datastax/cass-operator/tree/master/docs/user, from which the user can pick their relevant K8s version. Will fix.
