### ISSUE TITLE
Document connecting via the NGINX Ingress Controller

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#141]
_copy-paste description from high-level research_

### NGINX

[NGINX Ingress controller](https://docs.nginx.com/nginx-ingress-controller/overview/#nginx-ingress-controller) works with both NGINX and NGINX Plus and supports the standard Ingress features - content-based routing and TLS / SSL termination. Additionally, several NGINX and NGINX Plus features are available as extensions to the `Ingress` resource via annotations and the `ConfigMap` resource. In addition to HTTP, NGINX Ingress controller supports load balancing Websocket, gRPC, TCP, and UDP applications.

_Note_ that NGINX closely follows the k8s ingress specification and does **not** expose feature-rich configuration for TCP based protocols (like CQL). It is _possible_ to our preferred methods for deployment, but the configuration is less user-friendly compared to other approaches. These implementations are annotated appropriately below.

#### Sample Implementations

* Port-based load balancing _TBD_
* TLS based load balancing with mTLS _TBD_ **warning** advanced implementation
* TLS based load balancing with SNI & mTLS _TBD_ **warning** advanced implementation

**Comment by jimdickinson** [comment]
Closing here - will revisit as park of k8ssandra.
