### ISSUE TITLE
graph, solr, and spark support

### ISSUE THREAD

**Issue by SkySonR** [datastax/cass-operator#166]
As I can see the operator does not support graph, solr, and spark. Could you please document this also...
https://github.com/datastax/cass-operator/blob/26ad52bfc8f450852f5573fa2904a5df407ce2d3/operator/pkg/serverconfig/configgen.go#L17

It's blocker for as to start to use cass-operator instead of general helm installation which has multiple disadvantages compering to cass operator. But unfortunate we cannot use it right now... Do you have in roadmap support of graph, solr, and spark?

**Comment by jimdickinson** [comment]
There's a PR up right now to unblock testing additional workloads. We'll
cut a release by the end of July with that included, or you can make a
build off master after it merges, if you feel comfortable doing that.

**Comment by bradfordcp** [comment]
Related #167 , #158
