### ISSUE TITLE
Support single-node upgrade

### ISSUE THREAD

**Issue by grighetto** [datastax/cass-operator#255]
As part of a C* QA effort, we'd like to upgrade a single node in a C* cluster in order to test mixed-version scenarios.
We're using the cass-operator to spin up the test clusters, but to my knowledge the operator only supports single rack upgrades, that is, the entire rack.

**Comment by jsanda** [comment]
>to my knowledge the operator only supports single rack upgrades, that is, the entire rack.

I believe this is correct. cass-operator creates a StatefulSet per rack and uses the default update strategy which is `RollingUpdate`.  Let's say you change the `.spec.serverVersion` of your CassandraDatacenter. This will roll out the new image across all StatefulSets/racks in the cluster. You can limit the update to a single rack with `.spec.canaryUpgrade: true`.

The rolling update strategy of the StatefulSet has a `partition` property that allows you to control how many pods get updated. Only those pods whose ordinal index is >= `partition` will get updated. 

I like how CassKop handles updates. Like cass-operator it has a `Rack` type which exposes the partition property. By exposing the partition property at the rack level not only would you have fine-grained control over how many pods are updated, but you also have control over which racks get updated.

We would need to figure out what the behavior should be if both `.spec.canaryUpgrade` is `true` and the partition property at the rack level is modified. That should be easy enough though. 

I will work on a PR for this.

**Comment by jsanda** [comment]
After thinking about it some more, I think the `.spec.canaryUpgrade` property should be removed. By adding the `Partition` property as I have in PR #256 there is no need for `.spec.canaryUpgrade`. Removing it also simplifies the code a bit which is an added bonus.

**Comment by jimdickinson** [comment]
I disagree with removing `canaryUpgrade` for a few reasons. I think what you've added should be used in concert with it. Will leave more comments in the PR.

**Comment by jsanda** [comment]
Hi @grighetto 

I talked some @jimdickinson and he explained to me the idea of adding a `CanaryUpgradeCount` property. Since it would not be defined at the rack level, you would not be able to control in which rack the upgrade happens as I described above. You would however be able to upgrade a single node though. 

Is this sufficient for your use case?

**Comment by grighetto** [comment]
> Since it would not be defined at the rack level, you would not be able to control in which rack the upgrade happens

@jsanda yes, that totally works for me as long as the order of execution is consistent, that is, the upgrade doesn't happen at random racks at different times, such that the tests remain reproducible.

Thanks for the quick turnaround on this.

**Comment by jsanda** [comment]
@jimdickinson can we close this since #256 has been merged?

**Comment by jimdickinson** [comment]
Yes - I see we linked it but didn't use `fixes ...` so GH didn't handle it. Thanks for pointing it out!
