### ISSUE TITLE
K8S 1.18 cass-operator unable to pull image.

### ISSUE THREAD

**Issue by RobbieJVMW** [datastax/cass-operator#268]
**What Happened**

Following the installation guides deployment of the cass-operator using cass-operator-manifests-v1.18.yaml fails to pull a valid image from the repository.   Causing the operator to fail to start.  

[pullerror.log](https://github.com/datastax/cass-operator/files/5318155/pullerror.log)

(K8S version 1.18.6 )

**Comment by jimdickinson** [comment]
We've observed this before, and we've been trying to isolate what creates the problem. This is the issue...
```
  Warning  Failed     3m1s (x4 over 4m35s)   kubelet, ip-10-0-0-80.eu-west-2.compute.internal  Failed to pull image "datastax/cass-operator:1.4.1": rpc error: code = FailedPrecondition desc = failed to pull and unpack image "docker.io/datastax/cass-operator:1.4.1": failed commit on ref "layer-sha256:391dba5ec43113396bb1a701c2b3c8a160c560076e13a1c51759d35b4a6a64ae": "layer-sha256:391dba5ec43113396bb1a701c2b3c8a160c560076e13a1c51759d35b4a6a64ae" failed size validation: 146 != 147: failed precondition
```
Was this running with docker? or containerd?

**Comment by RobbieJVMW** [comment]
containerd

**Comment by jimdickinson** [comment]
@RobbieJVMW can you try again? I fixed some images that containerd checks wouldn't allow. It seems like we were effected by the same bug reported here - https://github.com/containers/skopeo/issues/1054

**Comment by RobbieJVMW** [comment]
Looks like the operator has successfully deployed.  I'll run some full tests to confirm.

**Comment by jimdickinson** [comment]
@RobbieJVMW let me know if we should reopen this.

**Comment by RobbieJVMW** [comment]
nope need to re-open looks good.
