### ISSUE TITLE
Feature request: label to differentiate all-pods-service from "ready" service

### ISSUE THREAD

**Issue by itzg** [datastax/cass-operator#276]
In version 1.4.1 of the operator, it creates the following two services `{cluster}-{dc}-all-pods-service` and `{cluster}-{dc}-service` that have identical labels, as shown here:

```
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE   LABELS
cluster1-dc1-all-pods-service   ClusterIP   None           <none>        9042/TCP,8080/TCP,9103/TCP   90m   app.kubernetes.io/managed-by=cass-operator,cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/datacenter=newflood-dc1
cluster1-dc1-service            ClusterIP   None           <none>        9042/TCP,8080/TCP,9103/TCP   90m   app.kubernetes.io/managed-by=cass-operator,cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/datacenter=newflood-dc1
```

I have adjusted a copy of the [generated service_monitor.yaml](https://github.com/datastax/metric-collector-for-apache-cassandra/blob/v0.1.11/dashboards/k8s-build/generated/prometheus/service_monitor.yaml) for monitoring with the prometheus operator. I was hoping to further adjust the service monitor to only select the "all-pods-service" since that is the service recommended for scraping; however, the [ServiceMonitorSpec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec) can only narrow to a label selector.

The scraping generally works fine except that both services are getting discovered and some of the stats report double the number of nodes. 

The duplicate discovery can be confirmed by looking at the targets view in Prometheus:

![image](https://user-images.githubusercontent.com/988985/95509507-3aacdf00-097a-11eb-85aa-2452df14e14f.png)

![image](https://user-images.githubusercontent.com/988985/95510148-17366400-097b-11eb-8b8f-c664b4ff350f.png)

Can the operator add an additional label to the "all-pods-service" that differentiates it from the other service? IMHO, it doesn't even need to be configurable, just something hardcoded would be good.

**Comment by jimdickinson** [comment]
great suggestion @itzg ! do you feel comfortable trying to make a PR? I think if you append a label on this line it will do what you want...

https://github.com/datastax/cass-operator/blob/73b010dfce267e289166ee8119431c96f7741774/operator/pkg/reconciliation/construct_service.go#L158

possibly `cassandra.datastax.com/prom-metrics: "true"`?

**Comment by itzg** [comment]
Thanks for the quick feedback! Sure, let me take a stab at a PR.
