### ISSUE TITLE
Creating a volume mount for the cassandra container 

### ISSUE THREAD

**Issue by navaganeshr** [datastax/cass-operator#281]
i am using cass-operator. I have  a init container which will create the keystore and truststore. I want to mount the same keystore and truststore on cassandra container. But in the custom resource definition where to add a entry to cassandra container to mount a volume. this is not clearly explained in it. 

below is my cassandraDatacentre resource

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: testcluster
  serverType: dse
  serverVersion: 6.8.3
  serverImage: "artifactory.example.com/datastax/dse-server:6.8.4-ubi7"
  configBuilderImage: "artifactory.example.com/datastax/cass-config-builder:1.0.3"
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: gp2-ebs-csi-default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  config:
    jvm-server-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"

    cassandra-yaml:
      num_tokens: 64
      allocate_tokens_for_local_replication_factor: 3
      backup_service:
        enabled: true
      file_cache_size_in_mb: 1000
      authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator
      authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer
      role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
      seed_provider:
        - class_name: org.apache.cassandra.locator.SimpleSeedProvider
          parameters:
            - seeds: "testcluster-seed-service,adca93d625cfa47077be145241e8.elb.ap-east-1.amazonaws.com"
  podTemplateSpec:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: dse-vault-init
          command:
            [
              "/bin/bash",
              "-c",
              "echo ${POD_NAME}.${NAMESPACE}.svc.cluster.local > /tmp/podname && sh /bin/entrypoint.sh ",
            ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: artifactory.example.com/nexus/platform-deployer:4e2bdc4
          imagePullPolicy: Always
          volumeMounts:
            - name: cert-sharing
              mountPath: /tmp/
            - name: dse-vault-init-entrypoint
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
      restartPolicy: Always
      containers:
        - name: audit-logs
          image: artifactory.example.com/busybox:latest
          imagePullPolicy: "Always"
          args:
            ["/bin/sh", "-c", "tail -n+1 -F /var/log/cassandra/audit/audit.log"]
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 100m
              memory: 64M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cassandra
              name: dse-audit-log
        - name: cassandra
          volumeMounts:
            **- mountPath: /opt/dse/resources/dse/conf/
              name: cert-sharing**
      volumes:
        - name: dse-init-config
          configMap:
            name: dse-vault-init-entrypoint-cm
            defaultMode: 0777
        **- name: cert-sharing
          emptyDir: {}**
        - name: dse-audit-log
          emptyDir: {}

**Comment by jimdickinson** [comment]
@navaganeshr adding new volumes mounts to the cassandra container was just merged to master in PR #263 - it will be in version 1.5.0 coming in the next weeks
