### ISSUE TITLE
Add the ability to set labels per rack

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#292]
In order to place pods of each rack in different locations, we need to be able to assign specific labels at the rack level. See https://orange-opensource.github.io/casskop/docs/5_operations/0_implementation_architecture#naming-convention-of-created-objects for an example. It's similar to zones but provides a better granularity.

**Comment by bradfordcp** [comment]
I'm a big fan of this approach vs the static zone identifier. 

@jimdickinson should we just add a new field in the rack, say `selector`, that accepts a free form set of key/value pairs? I'm in favor of deprecating the `zone` field altogether.

**Comment by jsanda** [comment]
>I'm in favor of deprecating the zone field altogether.

👍

**Comment by cscetbon** [comment]
@bradfordcp @jsanda let me know what you think about the changes I pushed. If we're on the same page I'll update the tests and the webhook
