### ISSUE TITLE
Backup/Restore ability for all users

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#308]
In CassKop 1.0.0 we implemented a backup/restore solution. We started to look at Velero but found the following issues:
- we needed to make some changes to the code to be able to only backup part of the filesystem
- we needed to make some changes to be able to restore part of the backup too
See https://github.com/vmware-tanzu/velero/issues/2361

We then collaborated with Instaclustr, developed a new backup and restore controllers and provided input to Instaclustr for the enhancement and development of [Icarus](https://github.com/instaclustr/instaclustr-icarus) and [Esop](https://github.com/instaclustr/instaclustr-esop) (we end up with one sidecar running on each pod). On the controllers side it's easy cause we have the ability to use a global request mode where we hit one of the nodes and it acts as a coordinator that talks to itself and all other nodes involved in the operation. It works with AWS, GCS and other cloud providers. It doesn't manage retention but we had in mind to propose the user to use life cycle management at the cloud provider's storage level to support it (https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html, https://cloud.google.com/storage/docs/lifecycle)

What we propose here is to add a backup/restore feature for all users and it can be done simply by incorporating our controllers with the icarus sidecars. However we don't want to enforce any solutions and we could adapt our controllers to work with Icarus and any other solution that you'd like to promote. But it is a crucial requirement.

I can walk you through the code but here are some links if you wanna take a look at it
- https://github.com/Orange-OpenSource/casskop/blob/master/deploy/crds/db.orange.com_cassandrabackups_crd.yaml
- https://github.com/Orange-OpenSource/casskop/blob/master/deploy/crds/db.orange.com_cassandrarestores_crd.yaml
- https://github.com/Orange-OpenSource/casskop/tree/master/pkg/controller/cassandrabackup
- https://github.com/Orange-OpenSource/casskop/tree/master/pkg/controller/cassandrarestore
- https://github.com/Orange-OpenSource/casskop/tree/master/pkg/cassandrabackup

**Comment by chienfuchen32** [comment]
Hi, here's another cloud based storage backup/restore approach.

* https://github.com/nuvo/cain
* https://github.com/helm/charts/blob/master/incubator/cassandra/templates/backup/cronjob.yaml
@jimdickinson Is it possible feasible solution in cass-operator? Thank you.

**Comment by jimdickinson** [comment]
We've been working on fully integrated Reaper support as part of K8ssandra (cc @jsanda)

@johnsmartco can we update the docs to remove the text and point to K8ssandra's Reaper docs?

**Comment by jsanda** [comment]
Hi @chienfuchen32 

Please check out https://github.com/k8ssandra/k8ssandra. It is built on top of cass-opertor and provides additional functionality such as repair and backup/restore. You might be interested in the backup/restore docs at https://k8ssandra.io/docs/topics/restore-a-backup/.

**Comment by jdonenine** [comment]
Both repair and backup/restore are more broadly part of k8ssandra now, so I'm closing out this issue.  If there are specific functionality gaps in either of those features within K8ssandra we can open issues for those specific items.

**Comment by jdonenine** [comment]
Migrated to https://github.com/k8ssandra/k8ssandra/issues/951
