### ISSUE TITLE
Crossed IPs handling

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#312]
Sometimes IPs from different cassandra nodes of the same cluster can be exchanged and in that case Cassandra refuses to start. CassKop introduced a fix to this issue described [here](https://orange-opensource.github.io/casskop/docs/3_configuration_deployment/9_advanced_configuration/#cross-ip-management).

What it does is store the host/ID map and when it sees that the map changed with an exchange of IPs from the previous time it collected it, it kills those pods and let k8s restart them.
The current code is available at https://github.com/Orange-OpenSource/casskop/blob/v1.0.0-release/pkg/controller/cassandracluster/reconcile.go#L708-L721 and https://github.com/Orange-OpenSource/casskop/blob/v1.0.0-release/pkg/controller/cassandracluster/reconcile.go#L751-L794). 

The goal of this ticket is have it handled in cass-operator.

**Comment by jdonenine** [comment]
Migrated over to https://github.com/k8ssandra/cass-operator/issues/130
