### ISSUE TITLE
kubectl plugin

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#315]
Another ticket to be casskop compatible by adding a plugin similar to [casskop plugin](https://orange-opensource.github.io/casskop/docs/2_setup/2_install_plugin/). The goal is to ease any operation to run on the cluster using a kubectl plugin with a simple set of commands. That plugin could also be used to simply create clusters by asking some questions and based on the answers building automatically the corresponding objects that cass-operator watches:

```
# Clean nodes in dc1
$ kubectl cass-operator clean dc1

# Trigger a rolling restart of nodes in rack rack1 and rack2 
$ kubectl cass-operator restart --crd my-crd --rack rack1 rack2
...
```

**Comment by jdonenine** [comment]
Migrated over to https://github.com/k8ssandra/k8ssandra/issues/937
