### ISSUE TITLE
Add ability to create multiple datacenters

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#318]
Another ticket to be CassKop compatible. We need to support multiple datacenters, for instance having on the same site one datacenter for regular workload and one for spark jobs. We had that discussion in the past and @jsanda made some proposals that could be used as a starting point or maybe a solution.

**Comment by cscetbon** [comment]
Okay I think we can close the ticket as the ability is already available at https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorUsing.html?hl=multi#Establishingamulti-datacentercluster. I also tested it using the same object and replacing its name.

**Comment by jimdickinson** [comment]
👍  I think we could still make multi-DC-in-one-k8s-cluster more automated, but we do support it with a rather long procedure to get it working.
