### ISSUE TITLE
Helm Chart 1.5.0 not available on charts index

### ISSUE THREAD

**Issue by tonyfahrion** [datastax/cass-operator#328]
Hi,

I tried to install the helm chart version 1.5.0 today, but figured out that only version 1.4.1 is available on https://datastax.github.io/charts.

Might this be an issue or is this done by intention?

Kind regards
Tony

**Comment by jimdickinson** [comment]
Thanks for the report - some automation failed, and we fixed it -> https://github.com/datastax/charts/commit/906dba2d47db1a37cd83566d3871075f1657d8ed

Please post back here if you've still got problems!
