### ISSUE TITLE
Write Logs on Filesystem 

### ISSUE THREAD

**Issue by DanielBrommer** [datastax/cass-operator#379]
Hi, 

Is there a way to add a PVC for "/var/log/cassandra" when running in a self-hosted environment with multiple Cassandra nodes ? 

Thank you and best regards, 
Daniel

**Comment by jsanda** [comment]
Hi @DanielBrommer 

See https://github.com/datastax/cass-operator/issues/327 for details on how to do it. The changes have been merged in master but not yet release. Let me know if you would like to see an example.

**Comment by DanielBrommer** [comment]
Hey @jsanda 

Thank you very much. 
Is there already a release date for this feature ? 
In #327 everything is described very well, that's enough for me. 

Kind regards 

Daniel

**Comment by DanielBrommer** [comment]
Is included in the 1.6.0 release 🥳
