### ISSUE TITLE
Host selector

### ISSUE THREAD

**Issue by robshep** [datastax/cass-operator#40]
Is it possible to use a host selector label to only put database cluster pods on specific hosts.

E.g. nodeSelectors in the operator-generated pod spec
or tolerations that we could apply traits for.

Thanks

**Comment by jimdickinson** [comment]
Hi @robshep - thanks for reaching out. It isn't possible with the current code, but it's something we've wanted to support, and we've been in the process of gathering use cases. Could you describe your k8s cluster topology a little bit so we can add the right feature to help you?

As things stand in 1.0.0, we have a spot in the rack configuration to pin a rack to a `failure-domain.beta.kubernetes.io/zone`, but I know that won't help enough in a fairly heterogenous k8s cluster.

**Comment by robshep** [comment]
Thank you for considering this. 

Yes, we have heterogeneous clusters with different grade hosts. The vast majority of other services survive happily on general purpose nodes and can be scheduled anywhere.  
We effectively want to provision a node pool specifically to support c7a clusters.
We can try and pin other general purpose services onto other nodes, but can't see a way of preventing cass-operator scheduling onto other types (by labels or traits, in my experience).  E.g. We have forthcoming a couple of nodes with GPU capability (for experimental stuff) - a cass pod would fit (but pretty much exhaust) such a node prohibiting gpu-specific pods from being scheduled (until, presumably (with no scheduling priority) the scheduler starts thrashing the cass pods around, which we'd like to avoid, of course)

I'd like to support our pre-production environment which is in-house, bare-metal style (comprised of very different physical hosts) and then allowing cost-effective use of resources as we migrate applications into production in a variety of cloud providers. 

I had considered just building a sibling k8s cluster out of specific nodes but we haven't quite worked out how to expose the active cassandra endpoints (cql and jmx) outside of the the cluster to another k8s effectively (both operationally and securely) maybe node-port will suffice ?

I happened to be perusing CrunchyData's postgres operator and noticed that they support node labels to target pods.     https://access.crunchydata.com/documentation/postgres-operator/4.2.2/configuration/pgo-yaml-configuration/  ;)  

Thanks for the effort, in any case,

**Comment by jimdickinson** [comment]
Yeah - I think we can add support for https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector and it will cover your use case. Do you think you'll also need taints/tolerations support to keep your other pods from becoming Cassandra neighbors?

**Comment by robshep** [comment]
Thank you.
Personally, our deployments are not sophisticated enough for this - everything else can be node-selected in a similar fashion. 
Thanks

Rob

**Comment by jimdickinson** [comment]
@robshep are you up for building from source, or would you like me to ping you next week when 1.0.1 goes out with this feature?

**Comment by robshep** [comment]
Thanks. I'll keep my eye out for the build, no rush.  Thanks a lot.

**Comment by jimdickinson** [comment]
@robshep Just released 1.1.0 which has the `nodeSelector` in the CassandraDatacenter, and it gets applied to all Cassandra pods. Let us know how it goes!
