### ISSUE TITLE
[BUG] PVC can be deleted mistakenly when reading stale deletionTimestamp information

### ISSUE THREAD

**Issue by srteam2020** [datastax/cass-operator#412]
### Description
We find that in a HA k8s cluster, cass-operator could mistakenly delete the PVC of the cassandra pod after cass-operator experiencing a restart. After diagnosis and inspection, we find it is caused by potential staleness in some of the apiserver.
More concretely, if cass-operator receives a stale update event from an apiserver saying "CassandraDatacenter has non-nil deletion timestamp", the controller will delete the PVCs returned by `listPVCs`, and `listPVCs` will list PVCs using the name(space) instead of the UID. Note that the stale event actually comes from the deletion of a previous CassandraDatacenter sharing the same name (but with a different UID) as the currently running one, so the PVC of the existing CassandraDatacenter will be listed and deleted mistakenly.
One potential approach to fix this is to label each PVC the UID of the CassandraDatacenter when creating them, and list the PVC using the UID of the CassandraDatacenter in `listPVCs` to ensure that we always delete the right PVC.

### Reproduction
We list concrete reproduction steps in a HA cluster as below:
1. Create a CassandraDatacenter `cdc`. PVC will be created in the cluster.
2. Delete `cdc`. Apiserver1 will send the update events with a non-nil deletion timestamp to the controller and the controller will trigger `deletePVCs()` to delete related PVC. Meanwhile, apiserver2 is partitioned so its watch cache stops at the moment that `cdc` is tagged with a deletion timestamp.
3. Create the CassandraDatacenter with the same name `cdc` again. Now the CassandraDatacenter gets back with a different uid, so as its PVC. However, apiserver2 still holds the stale view that `cdc` has a non-nil deletion timestamp and is about to be deleted.
4. The controller restarts after a node failure and talks to the stale apiserver2. Reading the stale update events from apiserver2 that `cdc` has a deletion timestamp, the controller lists all the PVC belonging to the currently running `cdc` (as mentioned above) and deletes them all.

### Fix
We are willing to help fix this bug by issuing a PR.
As mentioned above, the bug can be avoided by tagging each PVC with the UID of the CassandraDatacenter and listing PVC with UID. Each CassandraDatacenter will always have a different UID even with the same name. So in this case the PVCs belonging to the newly created CassandraDatacenter will not be deleted by the stale events of the old one.

**Comment by jsanda** [comment]
Hi @srteam2020 

Thanks for the detailed issue. The fix you describe sounds reasonable. 

Can the bug be reproduced consistently? (I assume the answer is no)

I would like to be able to reproduce the bug in order to properly verify the fix.

**Comment by srteam2020** [comment]
Hello @jsanda Thank you for the reply.
We send a PR for this https://github.com/datastax/cass-operator/pull/416

> Can the bug be reproduced consistently? (I assume the answer is no)

We are currently developing a tool to detect/reproduce the bugs that require intricate timing to manifest. Our tool can consistently detect/reproduce this bug. The tool is still in development so we are not able to release it yet. I will definitely let you know when we open the tool.

**Comment by jdonenine** [comment]
I've gone ahead and recreated this issue at https://github.com/k8ssandra/cass-operator/issues/118.

Let's discuss how to get the PR re-created there as well to address it.

Thanks!
