### ISSUE TITLE
[BUG] Redundant PVC deletion when Cassandra cluster is scaling down

### ISSUE THREAD

**Issue by srteam2020** [datastax/cass-operator#417]
### Description

We find that cass-operator triggers repeated pod PVC deletions during node decommission. 

When scaling down the cluster, cass-operator will delete pod's PVC in `CheckDecommissioningNodes` as long as the decommissioned pod still exists.
```GO
func (rc *ReconciliationContext) CheckDecommissioningNodes(epData httphelper.CassMetadataEndpoints) result.ReconcileResult {
	for _, pod := range rc.dcPods {
		if pod.Labels[api.CassNodeState] == stateDecommissioning {
			if !IsDoneDecommissioning(pod, epData) {
				...
			} else {
				rc.ReqLogger.Info("Node finished decommissioning")
				if res := rc.cleanUpAfterDecommissionedPod(pod); res != nil {
					return res
				}
			}
			return result.RequeueSoon(5)
		}
	}
        ...
}
```
Inside `cleanUpAfterDecommissionedPod`, controller directly deletes PVC without checking whether the PVC is destined to be deleted (with a non-nil deletionTimestamp). 
However, the decommissioned pod could last long before getting deleted, and its existence keeps triggering redundant PVC deletion in each round of reconcile(). A better approach here is to check whether the PVC has a non-nil `deletionTimestamp` before issuing redundant deletion. 

### Fix

We are willing to send a PR for this issue by checking `deletionTimestamp` of PVC before deleting them.

**Comment by jdonenine** [comment]
I've gone ahead and recreated this issue at https://github.com/k8ssandra/cass-operator/issues/117.

Thanks.
