### ISSUE TITLE
Spring data cassandra -  connection polling

### ISSUE THREAD

**Issue by pralow** [datastax/cass-operator#419]
Creating connection from the spring web application to the Cassandra Cluster(Cass operator) is trying to use the private IP of the pod (nodetool status ip). which would not be exposed outside. 

How to use Spring data connection polling without exposing the pod to the outside world ? 

Thanks,

**Comment by jdonenine** [comment]
Hi @pralow thanks for your question on the project.  As part of the expanding K8ssandra project we've recently migrated the cass-operator project to a new home at [k8ssandra/cass-operator](https://github.com/k8ssandra/cass-operator).  In the new repo is where we'll be continuing work on the project and publishing new releases from (we just recently released v1.7.0 and v1.7.1).

Spring Data integration is something that a number of folks in the K8ssandra team have experience with, so I'd love to get your issue moved over to the new repo for some discussion.

Would you want to recreate your issue over [there](https://github.com/k8ssandra/cass-operator/issues/new/choose) or I'd be happy to move it over for you real quick.

Let me know what you'd rather do.

Thanks!

**Comment by jdonenine** [comment]
I've gone ahead and recreated this at https://github.com/k8ssandra/cass-operator/issues/115

Thanks!
