### ISSUE TITLE
Not compatible with Istio service mesh

### ISSUE THREAD

**Issue by springstim** [datastax/cass-operator#422]
There are several things that could be done to make the Cass operator compatible with Istio service mesh; currently I think this Cassandra operator is not usable on Istil 1.8 and above.  Here are some suggestions to increase compatibility:

1. Remove the management API from the general services.    I could be wrong but I don't think there is value in putting the management API port (i.e. 8080) into the general services.  As soon as port 8080 appears in a service that has matching selectors for the pods, Istio no longer allows access to the datacenter pod's cluster IP.  

2. Instead of adding the management API port 8080 to the general statefulSet services, create  services for each datacenter StatefulSet member using the "**statefulset.kubernetes.io/pod-name**" selector; this way the DC pods can be referenced by a pod-specific service name

3. Do not have the operator attempt to connect to the DC pods via their clusterIPs as this is blocked by Istio sidecar proxies with mutual TLS enforced; instead use the pod-specific service names from "2." above.  This allows Istio's mutual TLS capability to be used; when using pod/clusterIPs, Istio needs to be in a PERMISSIVE state or the Datacenter pods cannot start.

TIA

**Comment by jdonenine** [comment]
Hi @springstim thanks for contributing the issue to the project.  As part of the expanding K8ssandra project we've recently migrated the cass-operator project to a new home at [k8ssandra/cass-operator](https://github.com/k8ssandra/cass-operator).  The new repo is where we'll be continuing work on the project and publishing new releases from (we just recently released v1.7.0 and v1.7.1).

Service mesh integration is something that we've started thinking about recently within K8ssandra so I'd love to get your issue moved over to the new repo for some discussion.

Would you want to recreate your issue over [there](https://github.com/k8ssandra/cass-operator/issues/new/choose) or I'd be happy to move it over for you real quick?

Let me know what you'd rather do.

Thanks!

**Comment by springstim** [comment]
Hi Jeff.  Sure, I’d be happy to re-create the issue on the new site.  I’m not an expert in service meshes but I’ve had some success tinkering with the Golang code to see if I could coax the operator image to play nicely with Istio.  I think I understand at least one way to at least get it working but I’m not really skilled with Golang enough to contribute directly.

**Comment by jdonenine** [comment]
I've gone ahead and recreated the issue at https://github.com/k8ssandra/cass-operator/issues/114

Thanks!
