### ISSUE TITLE
Support many of the fields from PodSpec in CassandraDatacenterSpec

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#54]
For example, see the implementation of `PrometheusSpec` at https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec.

Specifically fields like:

- imagePullSecrets
- volumes
- volumeMounts
- configMaps
- tolerations
- containers
- etc...

should exist and be passed through or merged with values generated by the operator to the underlying stateful sets. This allows for an **extreme** amount of flexibility in deployments. 

For example, if a user wants to use a custom log forwarder they could add an entry in the containers array.

**Comment by jgoeres** [comment]
When will we have a release with this change? In particular, I need imagePullSecrets for an environment with an internal registry that does not allow anonymous pull access.

**Comment by jimdickinson** [comment]
@jgoeres We're planning to cut a release this week - I'll ping you again when it's up. You can already use an internal registry by setting `serviceAccount` on the `cassdc` - would that work for you? You're right this feature does open up a more direct path for many customizations.

**Comment by jgoeres** [comment]
Thanks, I will give the serviceAccount-based approach a try.
Eagerly waiting for the release. :-)

**Comment by jimdickinson** [comment]
@jgoeres we released last Friday - let me know if you're able to hit your internal registry!
