### ISSUE TITLE
Documentation for Kind references old container names

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#57]
Now that the operator is GA the list of containers at `docs/developer/kind.md` should be updated to point at the GA containers.

- datastax/cass-operator:1.0.0
- datastax/cass-config-builder:1.0.0
- datastax/dse-server:6.8.0
- datastax/cassandra-mgmtapi-4_0_0:1.0.0
- datastax/cassandra-mgmtapi-3_11_6:1.0.0

**Comment by jimdickinson** [comment]
@sandoichi fixed this in #79
