### ISSUE TITLE
Failed to delete a cluster as shown in the documentation

### ISSUE THREAD

**Issue by datazef** [datastax/cass-operator#63]
It's not possible to delete a resource (using version 1.1.0) following the documentation commands. Below some of the different paths used, but all give the same results. 

kubectl delete cassdc/dc1 -n cass-operator
Error from server: admission webhook "cassandradatacenter-webhook.cassandra.datastax.com" denied the request: there is no content to decode

kubectl delete cassdcs --all-namespaces
error: resource(s) were provided, but no name, label selector, or --all flag specified

kubectl delete cassdcs --all-namespaces --all
Error from server: admission webhook "cassandradatacenter-webhook.cassandra.datastax.com" denied the request: there is no content to decode

**Comment by datazef** [comment]
1. If I recall correctly it was the lowest version available in GKE. 0.14.1?
2. Cluster is destroyed
3. GKE
4. MacOS & zsh

Next time I have the cluster operating, I will give it another try.

**Comment by sandoichi** [comment]
@datazef I was able to reproduce this using k8s < v1.15, and it should be resolved now. You will need to use an cass-operator image with tag [5ae9bee52608be3d2cd915e042b2424453ac531e](https://github.com/datastax/cass-operator/packages/174279?version=5ae9bee52608be3d2cd915e042b2424453ac531e) or newer in your cluster.
