### ISSUE TITLE
Improve deployment failure 

### ISSUE THREAD

**Issue by datazef** [datastax/cass-operator#64]
Created a config mismatch (by error): 
   - deployed k8s cluster in us-west1
   - configured a DSE deployment in zones outside of us-west.

Pods do not get started and stay in pending mode:
cluster1-dc1-rack1-sts-0         0/2     Pending   0          31m
cluster1-dc1-rack2-sts-0         0/2     Pending   0          31m
cluster1-dc1-rack3-sts-0         0/2     Pending   0          31m

No logs, cannot describe pod, cass-operator logs has nothing to show, kubectl events shows nothing... Not ideal to explain the problem. The GCP console shows POD as Unschedulable. 

The only solution found to retrieve the state is: kubectl get -o template pod/cluster1-dc1-rack1-sts-0    --template={{.status}} -n cass-operator

Would be great to understand what happen with this command: kubectl -n cass-operator get cassdc/dc1 -o "jsonpath={.status}" and provide and error stirng if possible.

**Comment by bradfordcp** [comment]
It's surprising that `kubectl describe pod cluster1-dc1-rack1-sts-0` didn't return anything. That's usually the first step when troubleshooting.

Can you share the status information you were able to retrieve?

**Comment by datazef** [comment]
At this point, the pod does not even exist and the describe command returns nothing. I will have to launch the cluster again to test. If you want to reproduce, deploy the cluster in region A and configure the racks to be in region B. The same error will be shown.

**Comment by bradfordcp** [comment]
Are you running your control plane in us-west and worker nodes in another region? How are you handling IP connectivity between the regions?

**Comment by datazef** [comment]
So, it was done as a mistake. I did not want to separate control plane from nodes. Just created like that and had a hard time understanding I had a bad setup. I hope this clarifies.

**Comment by jimdickinson** [comment]
I think we're on par with k8s in general as far as this ticket goes. You can use affinities / or node selector in ways that will never be satisfied. I think we can add this case to a FAQ we maintain. Opened #123 to capture this.
