### ISSUE TITLE
Support specifying a default image repository for all container images

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#92]
If I'm running the operator in an environment with a private registry it would be helpful to inform the operator where these images reside and have it use this location for all CassDCs. This keeps YAMLs clean as users won't have to specify the config builder and server image values if all of their images come from the same internal location.

With that being said even if a new default is specified a user should still be able to override the default on a per CassDC basis with the server image and config builder image fields.

From an implementation perspective, it would be nice to specify this as an environment variable or config map that is consumed by the operator deployment.

**Comment by bradfordcp** [comment]
To be clear this may reside in multiple environment variables like:

CASSANDRA_SERVER_IMAGE_REPOSITORY=datastax/cassandra_with_mgmt_api
DSE_SERVER_IMAGE_REPOSITORY=datastax/dse-server
CASS_CONFIG_BUILDER_IMAGE_REPOSITORY=datastax/cass-config-builder

**Comment by jimdickinson** [comment]
Fixed by https://github.com/datastax/cass-operator/pull/228
